### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by cursinorock** [ExpensiveKoala/Avaritia-and-RefinedStorage#5] opened 2018-08-19 05:26 UTC
Crash when game loads.
Just load with the mod on folder.

[crash-2018-08-19_02.13.57-client.txt](https://github.com/ExpensiveKoala/Refined-Avaritia/files/2300102/crash-2018-08-19_02.13.57-client.txt)

**Comment by ExpensiveKoala** [comment] 2018-08-19 20:50
This crash doesn't make sense. I see you're using the latest version of my mod, but nowhere am I using the `TableStackHandler` it's referencing.

I see some others are putting a 👍 so if anyone else has a crash report I can look at, please share them.

**Comment by GamertechAU** [comment] 2018-08-20 04:21
https://pastebin.com/xk6em3Yk

**Comment by Peach774** [comment] 2018-08-20 06:33
I'm also having the same issue. It seems to reference Extended Crafting, which is a mod I do not have

**Comment by cursinorock** [comment] 2018-08-20 18:46
the old version works fine here, just when i update this crash appears :T

**Comment by ExpensiveKoala** [comment] 2018-08-20 19:01
Yeah, I'm not really sure what the issue is. I have a theory though and will upload a jar for you guys to test here tonight.

**Comment by ExpensiveKoala** [comment] 2018-08-21 02:15
Can one of you test with this and tell me if it resolves the issue?
[refined_avaritia-1.12.2-2.2.zip](https://github.com/ExpensiveKoala/Refined-Avaritia/files/2304509/refined_avaritia-1.12.2-2.2.zip)

**Comment by cursinorock** [comment] 2018-08-21 03:35
yes and no. Now load the game but when you create a world or carry the worlds does not load at all. but do not crashs, just  freeze in load screen.
But if you can not reproduce, should be some problem between mods.

**Comment by Gebcrafter** [comment] 2018-08-21 03:47
I also have this issue, the crash references Extended Crafting, and the mod only initializes if Extended Crafting is installed.

**Comment by ExpensiveKoala** [comment] 2018-08-21 13:13
Cursinorock, does it produce any logs? I can't seem to reproduce that.

**Comment by cursinorock** [comment] 2018-08-21 18:20
Nop, just freeze and i have to kill the process :( 
I'll try again today, lets see if produces any log now

**Comment by cursinorock** [comment] 2018-08-21 18:46
i remove some mods and now works just fine :D

**Comment by ExpensiveKoala** [comment] 2018-08-21 23:49
Which mods did you remove? I want to be sure that it isn't caused by my mod before I release the fix for this officially

**Comment by cursinorock** [comment] 2018-08-22 00:18
Jurassic Craft
Tinkers compendium
Elemental pets
Lore Craft
Elder Arsenal
But i'm not sure if they're related, im creating a modpack soo bugs or no working mods are part of the process

**Comment by cursinorock** [comment] 2018-08-22 00:19
But for sure this version works better for me

**Comment by ExpensiveKoala** [comment] 2018-08-22 02:42
Okay. Then this issue should be resolved. I will officially release the update on curse tomorrow.

**Closed as completed by ExpensiveKoala** 2018-08-22 02:42 UTC
Labels: bug

**Comment by Peach774** [comment] 2018-08-22 03:06
I just tested. Confirmed that it worked for me as well. I realize its closed, just wanted to confirm that it is 100% fixed
